version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
